'on': 
  workflow_dispatch:
  schedule:
    - cron: 25 5 * * 1

name: build-and-release

jobs:
  build_pfaedle:
    parochial_merge: jobs/build_pfaedle

  build_osrm:
    parochial_merge: jobs/build_osrm

  download_and_prepare_terrain:
    parochial_merge: jobs/download_and_prepare_terrain

  download_and_prepare_osm:
    parochial_merge: jobs/download_and_prepare_osm

  prepare_street_graph:
    parochial_merge: jobs/prepare_street_graph

  prepare_osrm_graph:
    parochial_merge: jobs/prepare_osrm_graph

  download_and_prepare_atoc:
    parochial_merge: jobs/download_and_prepare_atoc

  download_and_prepare_tnds:
    parochial_merge: jobs/download_and_prepare_tnds

  download_and_prepare_bods:
    parochial_merge: jobs/download_and_prepare_bods

  merge_and_pfaedle_gtfs:
    parochial_merge: jobs/merge_and_pfaedle_gtfs

  prepare_pretty_map:
    parochial_merge: jobs/prepare_pretty_map

  prepare_final_graph:
    parochial_merge: jobs/prepare_final_graph

  prepare_r5r_network_dat:
    parochial_merge: jobs/prepare_r5r_network_dat

  release:
    parochial_merge: jobs/release

