on: workflow_dispatch
name: build-graph

jobs:
  build-graph:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ATOC_USERNAME: ${{ secrets.ATOC_USERNAME }}
      ATOC_PASSWORD: ${{ secrets.ATOC_PASSWORD }}
      TNDS_USERNAME: ${{ secrets.TNDS_USERNAME }}
      TNDS_PASSWORD: ${{ secrets.TNDS_USERNAME }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("devtools"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install osmium
        run: brew install osmium-tool

      - name: Write config.yml
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/config.yml
          contents: |
            default:
              atoc_username: !expr Sys.getenv("ATOC_USERNAME")
              atoc_password: !expr Sys.getenv("ATOC_PASSWORD")
              tnds_username: !expr Sys.getenv("TNDS_USERNAME")
              tnds_password: !expr Sys.getenv("TNDS_PASSWORD")
            
          trying_to_force: an empty line

      - name: Download and prepare OSM
        run: |
          devtools::load_all()
          options(timeout=240)
          download_and_prepare_osm()
        shell: Rscript {0}

      - name: Upload OSM artifact
        uses: actions/upload-artifact@v2
        with:
          name: wales_ish.osm.pbf
          path: output/wales_ish.osm.pbf
          if-no-files-found: error

      - name: Download and prepare ATOC GTFS
        run: |
          devtools::load_all()
          download_atoc()
          prepare_atoc_gtfs()
        shell: Rscript {0}

      - name: Upload ATOC GTFS artifact
        uses: actions/upload-artifact@v2
        with:
          name: atoc.walesish.gtfs.zip
          path: output/atoc.walesish.gtfs.zip
          if-no-files-found: error

      - name: Download and prepare TNDS GTFS
        run: |
          devtools::load_all()
          download_tnds()
          prepare_tnds_gtfs()
        shell: Rscript {0}

      - name: Upload TNDS GTFS artifact
        uses: actions/upload-artifact@v2
        with:
          name: wales.bus.walesish.gtfs.zip
          path: output/wales.bus.walesish.gtfs.zip
          if-no-files-found: error

      - name: Download and prepare BODS GTFS
        run: |
          devtools::load_all()
          download_and_prepare_bus_gtfs()
        shell: Rscript {0}

      - name: Upload BODS GTFS WM artifact
        uses: actions/upload-artifact@v2
        with:
          name: west_midlands.bus.walesish.gtfs.zip
          path: output/west_midlands.bus.walesish.gtfs.zip
          if-no-files-found: error

      - name: Upload BODS GTFS NW artifact
        uses: actions/upload-artifact@v2
        with:
          name: north_west.bus.walesish.gtfs.zip
          path: output/north_west.bus.walesish.gtfs.zip
          if-no-files-found: error

      - name: Upload BODS GTFS SW artifact
        uses: actions/upload-artifact@v2
        with:
          name: south_west.bus.walesish.gtfs.zip
          path: output/south_west.bus.walesish.gtfs.zip
          if-no-files-found: error

      - name: Prepare street graph
        run: |
          devtools::load_all()
          download_otp()
          prepare_street_graph()
        shell: Rscript {0}

      - name: Upload street graph artifact
        uses: actions/upload-artifact@v2
        with:
          name: streetGraph.obj
          path: output/streetGraph.obj
          if-no-files-found: error

      - name: Prepare transport graph
        run: |
          devtools::load_all()
          download_otp()
          prepare_street_graph()
        shell: Rscript {0}

      - name: Upload transport graph artifact
        uses: actions/upload-artifact@v2
        with:
          name: graph.obj
          path: output/graph.obj
          if-no-files-found: error



