on: workflow_dispatch
name: temp-check-config

jobs:
  temp-check-config:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ATOC_USERNAME: ${{ secrets.ATOC_USERNAME }}
      ATOC_PASSWORD: ${{ secrets.ATOC_PASSWORD }}
      TNDS_USERNAME: ${{ secrets.TNDS_USERNAME }}
      TNDS_PASSWORD: ${{ secrets.TNDS_USERNAME }}
    steps:
      - name: Write config.yml
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/config.yml
          contents: |
            default:
              atoc_username: !expr Sys.getenv("ATOC_USERNAME")
              atoc_password: !expr Sys.getenv("ATOC_PASSWORD")
              tnds_username: !expr Sys.getenv("TNDS_USERNAME")
              tnds_password: !expr Sys.getenv("TNDS_PASSWORD")

      - name: Upload config artifact
        uses: actions/upload-artifact@v2
        with:
          name: config.yml
          path: config.yml
          if-no-files-found: error
